# Generated by Django 4.2.5 on 2023-10-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for the stock quote.')),
                ('current_price', models.DecimalField(decimal_places=4, help_text="The current stock price. ('c')", max_digits=18)),
                ('change', models.DecimalField(decimal_places=4, help_text="The change in stock price. ('d')", max_digits=18)),
                ('percent_change', models.DecimalField(decimal_places=4, help_text="The percent change in stock price. ('dp')", max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=4, help_text="The high price of the day. ('h')", max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=4, help_text="The low price of the day. ('l')", max_digits=18)),
                ('open_price', models.DecimalField(decimal_places=4, help_text="The open price of the day. ('o')", max_digits=18)),
                ('prev_close_price', models.DecimalField(decimal_places=4, help_text="The previous closing price. ('pc')", max_digits=18)),
                ('time_stamp', models.IntegerField(help_text="The timestamp when the quote was retrieved. ('t')")),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.stock')),
            ],
        ),
    ]
