# Generated by Django 4.2.5 on 2023-09-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='The ticker associated with the stock.', max_length=10)),
                ('company', models.CharField(help_text='The name of the company that issued the stock.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for the stock price.')),
                ('price', models.DecimalField(decimal_places=4, help_text='The closing stock price.', max_digits=18)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which the sentiment score was calculated.')),
                ('score', models.DecimalField(decimal_places=16, help_text='The sentiment score.', max_digits=18)),
                ('recommendation', models.CharField(choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell')], help_text='The action recommended for the stock.', max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which the sentiment score was calculated.')),
                ('sentiment', models.IntegerField(choices=[(-1, 'Negative'), (0, 'Neutral'), (1, 'Positive')])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Abbreviated name of the portfolio.', max_length=20)),
                ('description', models.CharField(help_text='Description of the portfolio.', max_length=100)),
                ('stocks', models.ManyToManyField(to='stocks.stock')),
            ],
        ),
    ]
