# Generated by Django 4.2.5 on 2023-10-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key_text', models.CharField(help_text='Unique identifier made up of ticker symbol concatenated with the date ', max_length=50)),
                ('date', models.DateField(help_text='Date for which the recommendation was calculated.')),
                ('sentiment_score', models.CharField(choices=[('negative', 'Negative'), ('neutral', 'Neutral'), ('positive', 'Positive')], help_text='The sentiment score.', max_length=20)),
                ('stock_recommendation', models.CharField(choices=[('Strong Buy', 'Strong Buy'), ('Buy', 'Buy'), ('Hold', 'Hold'), ('Sell', 'Sell'), ('Strong Sell', 'Strong Sell')], help_text='The action recommended for the stock.', max_length=20)),
                ('total_recommendation', models.CharField(choices=[('Strong Buy', 'Strong Buy'), ('Buy', 'Buy'), ('Hold', 'Hold'), ('Sell', 'Sell'), ('Strong Sell', 'Strong Sell')], help_text='The final action recommended for the stock.', max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
